name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
        # go-version: [1.20.x, 1.21.x, 1.22.x]
        # platform: [ubuntu-latest, macos-latest]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - name: Build Docker Image
      run: docker build . --tag go-docker-image:$(date +%s)
    
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: hsiaohsiangruan/Waterfall-react
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,v0.5.5"